language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- iojs-1
- iojs-2
- iojs-3
- '4'
- '5'
- '6'
notifications:
  slack:
    secure: FhvFi2JBDeyrmax2TugZc0RlDsjh/XBRh2L+PwLep1Mh+gk+AuUJ2OeXyS1I3qIsQvNm+wvDkUdfP38w1FYA5B10499iZhScOowg88b75Zt2G8bnDvxb++L/IQh32usaAeDQSfziNJ//7RPc+pi2tO8fFXsPZNlrBmvi6pnjtKobcFIwE1F8f6mWOLopX/WrUWVdJjEpRq73PPIOFdxF4ufM2orMBkrkd7hc1Q0YL4hYtHPrmkoGGImOknfnT3zqSYc6ROSiMZo/EzJvqE30Dkz0gLVrgBz36kd8sVQyE+fFH2J00uSw18XHNT9rE1DeTQSqrM1QBiZkNCV/Bk9yfEljN8/vitODd9E7Y87D4jsW0aZVOYhIgeOFXsC1pmThg9Ec6Wr7NGGaywj5ws7Z8RWeE2uo6EvDf+4s9dv4VJnfuAlbCV6f6FfI49mj6kJNYMToonpvpRtFMFxC/iEAVQ7Ra+MXSXlOakvB7HfeTDi4nYJi3DqJDxD3ZrouatkSp5YHIOARar46X2zBP+vDTlBtjaFsBPFZfIMyK44WtehYrFrTonObj7e4rkpVtTNxeGQ8W/vzNfRuYgHZQe6EVXgZ0dPRQLDytXmpU0mGFhWdTdFGByNjtLXL1xHfHiCcARixu8OuBA8Si5KS8z5e2kCcVxvdb+hmfjVs+o8unho=
